-- ===========================================================================
-- GENERATED by seed_fake_pk_data.mjs. Do not hand-edit -- rerun the script.
-- Paste this whole file into the Supabase SQL editor and run it once, after
-- seed_fake_pk_data.mjs has created the auth accounts.
-- Safe to re-run.
-- ===========================================================================

do $fake$
declare
  v_admin uuid;
  v_clinic_0 uuid;
  v_clinic_1 uuid;
  v_clinic_2 uuid;
  v_lab_0 uuid;
  v_lab_1 uuid;
  v_uid uuid;
begin
  -- Clinics ------------------------------------------------------------------
  select id into v_clinic_0 from public.clinics where name = 'Al-Shifa Medical Center';
  if v_clinic_0 is null then
    insert into public.clinics (name, type, phone, address_street, address_city, address_province, status)
    values ('Al-Shifa Medical Center', 'clinic', '04236000001', '45 Ferozepur Road', 'Lahore', 'Punjab', 'active')
    returning id into v_clinic_0;
  end if;
  select id into v_clinic_1 from public.clinics where name = 'City Care Clinic';
  if v_clinic_1 is null then
    insert into public.clinics (name, type, phone, address_street, address_city, address_province, status)
    values ('City Care Clinic', 'clinic', '02135000002', '12 Shahrah-e-Faisal', 'Karachi', 'Sindh', 'active')
    returning id into v_clinic_1;
  end if;
  select id into v_clinic_2 from public.clinics where name = 'Margalla Health Clinic';
  if v_clinic_2 is null then
    insert into public.clinics (name, type, phone, address_street, address_city, address_province, status)
    values ('Margalla Health Clinic', 'clinic', '05112000003', 'F-8 Markaz', 'Islamabad', 'Islamabad Capital Territory', 'active')
    returning id into v_clinic_2;
  end if;
  -- Diagnostic labs ------------------------------------------------------------
  select id into v_lab_0 from public.diagnostic_labs where name = 'Punjab Diagnostic Lab';
  if v_lab_0 is null then
    insert into public.diagnostic_labs (name, license_number, phone, address_city, address_province, status)
    values ('Punjab Diagnostic Lab', 'LAB-PB-2201', '04136000004', 'Faisalabad', 'Punjab', 'active')
    returning id into v_lab_0;
  end if;
  select id into v_lab_1 from public.diagnostic_labs where name = 'Sindh Central Laboratory';
  if v_lab_1 is null then
    insert into public.diagnostic_labs (name, license_number, phone, address_city, address_province, status)
    values ('Sindh Central Laboratory', 'LAB-SD-3305', '02137000005', 'Karachi', 'Sindh', 'active')
    returning id into v_lab_1;
  end if;
  -- Extra admin ------------------------------------------------------------
  select id into v_admin from auth.users where email = 'fake.admin@hayaatfake.id';
  if v_admin is not null then
    update public.profiles set role = 'admin', status = 'active', cnic = '3520205000001' where id = v_admin;
    insert into public.admin_profiles (id, admin_level, can_approve_doctors, can_approve_labs, can_suspend_accounts)
    values (v_admin, 'support_admin', true, true, false)
    on conflict (id) do update set admin_level = 'support_admin';
  end if;
  -- Doctors: approve + assign to a clinic (round-robin) ---------------------
  select id into v_uid from auth.users where email = 'dr.ahmed.hussain1@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '3520203000001' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50000', 'General Medicine', true, true,
       3, 1000, true, v_clinic_0, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.fatima.raza2@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '4210103000011' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50001', 'Cardiology', true, false,
       4, 1500, true, v_clinic_1, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.usman.iqbal3@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '6110103000021' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50002', 'Dermatology', true, true,
       5, 2000, true, v_clinic_2, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.hina.farooq4@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '3740503000031' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50003', 'Pediatrics', true, false,
       6, 2500, true, v_clinic_0, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.hamza.qureshi5@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '3310003000041' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50004', 'Orthopedics', true, true,
       7, 3000, true, v_clinic_1, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.sadia.baig6@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '3630203000051' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50005', 'Gynecology', true, false,
       8, 3500, true, v_clinic_2, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.imran.abbasi7@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '1730103000061' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50006', 'ENT', true, true,
       9, 1000, true, v_clinic_0, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  select id into v_uid from auth.users where email = 'dr.iqra.awan8@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set status = 'active', cnic = '5440003000071' where id = v_uid;
    insert into public.doctor_profiles
      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,
       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)
    values
      (v_uid, 'PMDC-50007', 'Psychiatry', true, false,
       10, 1500, true, v_clinic_1, now(), v_admin)
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, is_available = true,
          approved_at = coalesce(public.doctor_profiles.approved_at, now()),
          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);
  end if;
  -- Lab workers ---------------------------------------------------------------
  select id into v_uid from auth.users where email = 'ahmed.hussain1.lab@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'lab_worker', status = 'active', cnic = '3520204000001' where id = v_uid;
    insert into public.lab_worker_profiles (id, lab_id, employee_id, position_title, approved_at)
    values (v_uid, v_lab_0, 'LAB-FAKE-001', 'Lab Technician', now())
    on conflict (id) do update
      set lab_id = excluded.lab_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.lab_worker_profiles.approved_at, now());
  end if;
  select id into v_uid from auth.users where email = 'fatima.raza2.lab@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'lab_worker', status = 'active', cnic = '4210104000011' where id = v_uid;
    insert into public.lab_worker_profiles (id, lab_id, employee_id, position_title, approved_at)
    values (v_uid, v_lab_1, 'LAB-FAKE-002', 'Senior Lab Technician', now())
    on conflict (id) do update
      set lab_id = excluded.lab_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.lab_worker_profiles.approved_at, now());
  end if;
  select id into v_uid from auth.users where email = 'usman.iqbal3.lab@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'lab_worker', status = 'active', cnic = '6110104000021' where id = v_uid;
    insert into public.lab_worker_profiles (id, lab_id, employee_id, position_title, approved_at)
    values (v_uid, v_lab_0, 'LAB-FAKE-003', 'Phlebotomist', now())
    on conflict (id) do update
      set lab_id = excluded.lab_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.lab_worker_profiles.approved_at, now());
  end if;
  -- Receptionists --------------------------------------------------------------
  select id into v_uid from auth.users where email = 'ahmed.hussain1.front@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'receptionist', status = 'active', cnic = '3520204500001' where id = v_uid;
    insert into public.receptionist_profiles (id, clinic_id, employee_id, approved_at)
    values (v_uid, v_clinic_0, 'REC-FAKE-001', now())
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.receptionist_profiles.approved_at, now());
  end if;
  select id into v_uid from auth.users where email = 'fatima.raza2.front@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'receptionist', status = 'active', cnic = '4210104500011' where id = v_uid;
    insert into public.receptionist_profiles (id, clinic_id, employee_id, approved_at)
    values (v_uid, v_clinic_1, 'REC-FAKE-002', now())
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.receptionist_profiles.approved_at, now());
  end if;
  select id into v_uid from auth.users where email = 'usman.iqbal3.front@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set role = 'receptionist', status = 'active', cnic = '6110104500021' where id = v_uid;
    insert into public.receptionist_profiles (id, clinic_id, employee_id, approved_at)
    values (v_uid, v_clinic_2, 'REC-FAKE-003', now())
    on conflict (id) do update
      set clinic_id = excluded.clinic_id, employee_id = excluded.employee_id,
          approved_at = coalesce(public.receptionist_profiles.approved_at, now());
  end if;
  -- Patients: CNIC backfill + address/emergency contact ------------------------
  select id into v_uid from auth.users where email = 'ahmed.hussain1@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3520202000001' where id = v_uid and cnic is distinct from '3520202000001';
    update public.patient_profiles set
      address_city = 'Lahore', address_province = 'Punjab',
      emergency_contact_name = 'Nadia Abbasi', emergency_contact_phone = '03210500000'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'fatima.raza2@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '4210102000011' where id = v_uid and cnic is distinct from '4210102000011';
    update public.patient_profiles set
      address_city = 'Karachi', address_province = 'Sindh',
      emergency_contact_name = 'Kashif Awan', emergency_contact_phone = '03220500001'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'usman.iqbal3@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '6110102000021' where id = v_uid and cnic is distinct from '6110102000021';
    update public.patient_profiles set
      address_city = 'Islamabad', address_province = 'Islamabad Capital Territory',
      emergency_contact_name = 'Zainab Tariq', emergency_contact_phone = '03230500002'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'hina.farooq4@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3740502000031' where id = v_uid and cnic is distinct from '3740502000031';
    update public.patient_profiles set
      address_city = 'Rawalpindi', address_province = 'Punjab',
      emergency_contact_name = 'Zeeshan Javed', emergency_contact_phone = '03240500003'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'hamza.qureshi5@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3310002000041' where id = v_uid and cnic is distinct from '3310002000041';
    update public.patient_profiles set
      address_city = 'Faisalabad', address_province = 'Punjab',
      emergency_contact_name = 'Rabia Siddiqui', emergency_contact_phone = '03250500004'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'sadia.baig6@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3630202000051' where id = v_uid and cnic is distinct from '3630202000051';
    update public.patient_profiles set
      address_city = 'Multan', address_province = 'Punjab',
      emergency_contact_name = 'Junaid Mirza', emergency_contact_phone = '03260500005'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'imran.abbasi7@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '1730102000061' where id = v_uid and cnic is distinct from '1730102000061';
    update public.patient_profiles set
      address_city = 'Peshawar', address_province = 'Khyber Pakhtunkhwa',
      emergency_contact_name = 'Farah Rana', emergency_contact_phone = '03270500006'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'iqra.awan8@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '5440002000071' where id = v_uid and cnic is distinct from '5440002000071';
    update public.patient_profiles set
      address_city = 'Quetta', address_province = 'Balochistan',
      emergency_contact_name = 'Naveed Gill', emergency_contact_phone = '03280500007'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'waqas.tariq9@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3410102000081' where id = v_uid and cnic is distinct from '3410102000081';
    update public.patient_profiles set
      address_city = 'Sialkot', address_province = 'Punjab',
      emergency_contact_name = 'Bushra Cheema', emergency_contact_phone = '03290500008'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'amna.javed10@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3430102000091' where id = v_uid and cnic is distinct from '3430102000091';
    update public.patient_profiles set
      address_city = 'Gujranwala', address_province = 'Punjab',
      emergency_contact_name = 'Tariq Dar', emergency_contact_phone = '03300500009'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'asad.siddiqui11@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3520202000101' where id = v_uid and cnic is distinct from '3520202000101';
    update public.patient_profiles set
      address_city = 'Lahore', address_province = 'Punjab',
      emergency_contact_name = 'Saba Bhatti', emergency_contact_phone = '03310500010'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'sobia.mirza12@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '4210102000111' where id = v_uid and cnic is distinct from '4210102000111';
    update public.patient_profiles set
      address_city = 'Karachi', address_province = 'Sindh',
      emergency_contact_name = 'Adeel Niazi', emergency_contact_phone = '03320500011'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'faisal.rana13@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '6110102000121' where id = v_uid and cnic is distinct from '6110102000121';
    update public.patient_profiles set
      address_city = 'Islamabad', address_province = 'Islamabad Capital Territory',
      emergency_contact_name = 'Mehwish Khan', emergency_contact_phone = '03330500012'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'kiran.gill14@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3740502000131' where id = v_uid and cnic is distinct from '3740502000131';
    update public.patient_profiles set
      address_city = 'Rawalpindi', address_province = 'Punjab',
      emergency_contact_name = 'Hassan Ahmed', emergency_contact_phone = '03340500013'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'shahzad.cheema15@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3310002000141' where id = v_uid and cnic is distinct from '3310002000141';
    update public.patient_profiles set
      address_city = 'Faisalabad', address_province = 'Punjab',
      emergency_contact_name = 'Sidra Ali', emergency_contact_phone = '03350500014'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'uzma.dar16@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3630202000151' where id = v_uid and cnic is distinct from '3630202000151';
    update public.patient_profiles set
      address_city = 'Multan', address_province = 'Punjab',
      emergency_contact_name = 'Omar Malik', emergency_contact_phone = '03360500015'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'rizwan.bhatti17@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '1730102000161' where id = v_uid and cnic is distinct from '1730102000161';
    update public.patient_profiles set
      address_city = 'Peshawar', address_province = 'Khyber Pakhtunkhwa',
      emergency_contact_name = 'Komal Butt', emergency_contact_phone = '03370500016'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'nida.niazi18@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '5440002000171' where id = v_uid and cnic is distinct from '5440002000171';
    update public.patient_profiles set
      address_city = 'Quetta', address_province = 'Balochistan',
      emergency_contact_name = 'Yasir Sheikh', emergency_contact_phone = '03380500017'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'saad.khan19@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3410102000181' where id = v_uid and cnic is distinct from '3410102000181';
    update public.patient_profiles set
      address_city = 'Sialkot', address_province = 'Punjab',
      emergency_contact_name = 'Rukhsana Chaudhry', emergency_contact_phone = '03390500018'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'anum.ahmed20@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3430102000191' where id = v_uid and cnic is distinct from '3430102000191';
    update public.patient_profiles set
      address_city = 'Gujranwala', address_province = 'Punjab',
      emergency_contact_name = 'Ahmed Hussain', emergency_contact_phone = '03400500019'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'danish.ali21@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3520202000201' where id = v_uid and cnic is distinct from '3520202000201';
    update public.patient_profiles set
      address_city = 'Lahore', address_province = 'Punjab',
      emergency_contact_name = 'Fatima Raza', emergency_contact_phone = '03410500020'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'warda.malik22@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '4210102000211' where id = v_uid and cnic is distinct from '4210102000211';
    update public.patient_profiles set
      address_city = 'Karachi', address_province = 'Sindh',
      emergency_contact_name = 'Usman Iqbal', emergency_contact_phone = '03420500021'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'salman.butt23@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '6110102000221' where id = v_uid and cnic is distinct from '6110102000221';
    update public.patient_profiles set
      address_city = 'Islamabad', address_province = 'Islamabad Capital Territory',
      emergency_contact_name = 'Hina Farooq', emergency_contact_phone = '03430500022'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'aliya.sheikh24@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3740502000231' where id = v_uid and cnic is distinct from '3740502000231';
    update public.patient_profiles set
      address_city = 'Rawalpindi', address_province = 'Punjab',
      emergency_contact_name = 'Hamza Qureshi', emergency_contact_phone = '03440500023'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'arslan.chaudhry25@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3310002000241' where id = v_uid and cnic is distinct from '3310002000241';
    update public.patient_profiles set
      address_city = 'Faisalabad', address_province = 'Punjab',
      emergency_contact_name = 'Sadia Baig', emergency_contact_phone = '03450500024'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'ayesha.hussain26@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3630202000251' where id = v_uid and cnic is distinct from '3630202000251';
    update public.patient_profiles set
      address_city = 'Multan', address_province = 'Punjab',
      emergency_contact_name = 'Imran Abbasi', emergency_contact_phone = '03460500025'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'ali.raza27@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '1730102000261' where id = v_uid and cnic is distinct from '1730102000261';
    update public.patient_profiles set
      address_city = 'Peshawar', address_province = 'Khyber Pakhtunkhwa',
      emergency_contact_name = 'Iqra Awan', emergency_contact_phone = '03470500026'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'sana.iqbal28@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '5440002000271' where id = v_uid and cnic is distinct from '5440002000271';
    update public.patient_profiles set
      address_city = 'Quetta', address_province = 'Balochistan',
      emergency_contact_name = 'Waqas Tariq', emergency_contact_phone = '03480500027'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'bilal.farooq29@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3410102000281' where id = v_uid and cnic is distinct from '3410102000281';
    update public.patient_profiles set
      address_city = 'Sialkot', address_province = 'Punjab',
      emergency_contact_name = 'Amna Javed', emergency_contact_phone = '03490500028'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'mariam.qureshi30@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3430102000291' where id = v_uid and cnic is distinct from '3430102000291';
    update public.patient_profiles set
      address_city = 'Gujranwala', address_province = 'Punjab',
      emergency_contact_name = 'Asad Siddiqui', emergency_contact_phone = '03500500029'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'fahad.baig31@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3520202000301' where id = v_uid and cnic is distinct from '3520202000301';
    update public.patient_profiles set
      address_city = 'Lahore', address_province = 'Punjab',
      emergency_contact_name = 'Sobia Mirza', emergency_contact_phone = '03510500030'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'nadia.abbasi32@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '4210102000311' where id = v_uid and cnic is distinct from '4210102000311';
    update public.patient_profiles set
      address_city = 'Karachi', address_province = 'Sindh',
      emergency_contact_name = 'Faisal Rana', emergency_contact_phone = '03520500031'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'kashif.awan33@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '6110102000321' where id = v_uid and cnic is distinct from '6110102000321';
    update public.patient_profiles set
      address_city = 'Islamabad', address_province = 'Islamabad Capital Territory',
      emergency_contact_name = 'Kiran Gill', emergency_contact_phone = '03530500032'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'zainab.tariq34@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3740502000331' where id = v_uid and cnic is distinct from '3740502000331';
    update public.patient_profiles set
      address_city = 'Rawalpindi', address_province = 'Punjab',
      emergency_contact_name = 'Shahzad Cheema', emergency_contact_phone = '03540500033'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'zeeshan.javed35@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3310002000341' where id = v_uid and cnic is distinct from '3310002000341';
    update public.patient_profiles set
      address_city = 'Faisalabad', address_province = 'Punjab',
      emergency_contact_name = 'Uzma Dar', emergency_contact_phone = '03550500034'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'rabia.siddiqui36@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3630202000351' where id = v_uid and cnic is distinct from '3630202000351';
    update public.patient_profiles set
      address_city = 'Multan', address_province = 'Punjab',
      emergency_contact_name = 'Rizwan Bhatti', emergency_contact_phone = '03560500035'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'junaid.mirza37@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '1730102000361' where id = v_uid and cnic is distinct from '1730102000361';
    update public.patient_profiles set
      address_city = 'Peshawar', address_province = 'Khyber Pakhtunkhwa',
      emergency_contact_name = 'Nida Niazi', emergency_contact_phone = '03570500036'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'farah.rana38@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '5440002000371' where id = v_uid and cnic is distinct from '5440002000371';
    update public.patient_profiles set
      address_city = 'Quetta', address_province = 'Balochistan',
      emergency_contact_name = 'Saad Khan', emergency_contact_phone = '03580500037'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'naveed.gill39@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3410102000381' where id = v_uid and cnic is distinct from '3410102000381';
    update public.patient_profiles set
      address_city = 'Sialkot', address_province = 'Punjab',
      emergency_contact_name = 'Anum Ahmed', emergency_contact_phone = '03590500038'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'bushra.cheema40@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3430102000391' where id = v_uid and cnic is distinct from '3430102000391';
    update public.patient_profiles set
      address_city = 'Gujranwala', address_province = 'Punjab',
      emergency_contact_name = 'Danish Ali', emergency_contact_phone = '03600500039'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'tariq.dar41@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3520202000401' where id = v_uid and cnic is distinct from '3520202000401';
    update public.patient_profiles set
      address_city = 'Lahore', address_province = 'Punjab',
      emergency_contact_name = 'Warda Malik', emergency_contact_phone = '03210500040'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'saba.bhatti42@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '4210102000411' where id = v_uid and cnic is distinct from '4210102000411';
    update public.patient_profiles set
      address_city = 'Karachi', address_province = 'Sindh',
      emergency_contact_name = 'Salman Butt', emergency_contact_phone = '03220500041'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'adeel.niazi43@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '6110102000421' where id = v_uid and cnic is distinct from '6110102000421';
    update public.patient_profiles set
      address_city = 'Islamabad', address_province = 'Islamabad Capital Territory',
      emergency_contact_name = 'Aliya Sheikh', emergency_contact_phone = '03230500042'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'mehwish.khan44@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3740502000431' where id = v_uid and cnic is distinct from '3740502000431';
    update public.patient_profiles set
      address_city = 'Rawalpindi', address_province = 'Punjab',
      emergency_contact_name = 'Arslan Chaudhry', emergency_contact_phone = '03240500043'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'hassan.ahmed45@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3310002000441' where id = v_uid and cnic is distinct from '3310002000441';
    update public.patient_profiles set
      address_city = 'Faisalabad', address_province = 'Punjab',
      emergency_contact_name = 'Ayesha Hussain', emergency_contact_phone = '03250500044'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'sidra.ali46@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3630202000451' where id = v_uid and cnic is distinct from '3630202000451';
    update public.patient_profiles set
      address_city = 'Multan', address_province = 'Punjab',
      emergency_contact_name = 'Ali Raza', emergency_contact_phone = '03260500045'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'omar.malik47@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '1730102000461' where id = v_uid and cnic is distinct from '1730102000461';
    update public.patient_profiles set
      address_city = 'Peshawar', address_province = 'Khyber Pakhtunkhwa',
      emergency_contact_name = 'Sana Iqbal', emergency_contact_phone = '03270500046'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'komal.butt48@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '5440002000471' where id = v_uid and cnic is distinct from '5440002000471';
    update public.patient_profiles set
      address_city = 'Quetta', address_province = 'Balochistan',
      emergency_contact_name = 'Bilal Farooq', emergency_contact_phone = '03280500047'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'yasir.sheikh49@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3410102000481' where id = v_uid and cnic is distinct from '3410102000481';
    update public.patient_profiles set
      address_city = 'Sialkot', address_province = 'Punjab',
      emergency_contact_name = 'Mariam Qureshi', emergency_contact_phone = '03290500048'
    where id = v_uid;
  end if;
  select id into v_uid from auth.users where email = 'rukhsana.chaudhry50@hayaatfake.id';
  if v_uid is not null then
    update public.profiles set cnic = '3430102000491' where id = v_uid and cnic is distinct from '3430102000491';
    update public.patient_profiles set
      address_city = 'Gujranwala', address_province = 'Punjab',
      emergency_contact_name = 'Fahad Baig', emergency_contact_phone = '03300500049'
    where id = v_uid;
  end if;

  raise notice 'Fake Pakistani test data promotion complete.';
end;
$fake$;
