-- ===========================================================================
-- GENERATED by seed_research_account.mjs. Paste into the Supabase SQL editor.
-- Creates the demo research organisation and promotes the seeded account to
-- the `researcher` role. Safe to re-run.
-- ===========================================================================

do $research$
declare
  v_org uuid;
  v_uid uuid;
begin
  select id into v_org from public.research_organizations
   where name = 'Punjab Health Research Institute';
  if v_org is null then
    insert into public.research_organizations
      (name, organization_type, registration_number, contact_email,
       status, dpa_accepted_at, dpa_version, approved_at)
    values
      ('Punjab Health Research Institute', 'academic',
       'PHRI-2026-0044', 'data@phri.example.org',
       'active', now(), '2026-07-04', now())
    returning id into v_org;
  else
    update public.research_organizations set status = 'active' where id = v_org;
  end if;

  select id into v_uid from auth.users where email = 'researcher@hayaatfake.id';
  if v_uid is null then
    raise exception 'Researcher auth account missing. Run seed_research_account.mjs first.';
  end if;

  update public.profiles
     set role = 'researcher', status = 'active', cnic = '3520209000001'
   where id = v_uid;

  -- The account signed up as a patient, so it has a patient_profiles row and
  -- may hold clinical data of its own. Remove it: a researcher must never be a
  -- data subject inside the pool they can query.
  delete from public.patient_profiles where id = v_uid;

  insert into public.researcher_profiles (id, organization_id, job_title, is_org_admin)
  values (v_uid, v_org, 'Principal Investigator', true)
  on conflict (id) do update
    set organization_id = excluded.organization_id,
        is_org_admin = true;

  raise notice 'Researcher ready: % in org %', 'researcher@hayaatfake.id', v_org;
end;
$research$;
