// Creates a demo research organisation and researcher account.
//
//   node supabase/tests/seed_research_account.mjs
//
// Self-service sign-up is clamped to patient/doctor, so this script creates the
// auth account through the ordinary public API and then writes
// research_account_promote.generated.sql, which you paste into the Supabase SQL
// editor to create the organisation and promote the account to `researcher`.
//
// Prerequisite: supabase/research_platform.sql has been applied.

import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const URL = process.env.SUPABASE_URL || 'https://iikwdtiqvxxatrzahuzo.supabase.co';
const KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_4axuKG5-YTuZeHuuzZjuVw_cB5_h-xn';

export const RESEARCHER = {
  email: 'researcher@hayaatfake.id',
  password: process.env.FAKE_PASSWORD || 'Hayaat@2026',
  full_name: 'Dr. Nadia Rahman',
  phone: '03219000001',
  cnic: '3520209000001',
};

export const ORGANIZATION = {
  name: 'Punjab Health Research Institute',
  organization_type: 'academic',
  registration_number: 'PHRI-2026-0044',
  contact_email: 'data@phri.example.org',
};

const sqlStr = (s) => `'${String(s).replace(/'/g, "''")}'`;

async function main() {
  const client = createClient(URL, KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { error } = await client.auth.signUp({
    email: RESEARCHER.email,
    password: RESEARCHER.password,
    options: {
      data: {
        role: 'patient', // clamped anyway; promoted to researcher by the SQL below
        full_name: RESEARCHER.full_name,
        phone: RESEARCHER.phone,
        cnic: RESEARCHER.cnic,
        email: RESEARCHER.email,
      },
    },
  });

  if (!error) {
    console.log(`created   ${RESEARCHER.email}`);
  } else if (/already registered|already been registered/i.test(error.message)) {
    console.log(`exists    ${RESEARCHER.email}`);
  } else {
    console.log(`FAILED    ${RESEARCHER.email}: ${error.message}`);
    process.exitCode = 1;
    return;
  }
  await client.auth.signOut();

  const sql = `-- ===========================================================================
-- GENERATED by seed_research_account.mjs. Paste into the Supabase SQL editor.
-- Creates the demo research organisation and promotes the seeded account to
-- the \`researcher\` role. Safe to re-run.
-- ===========================================================================

do $research$
declare
  v_org uuid;
  v_uid uuid;
begin
  select id into v_org from public.research_organizations
   where name = ${sqlStr(ORGANIZATION.name)};
  if v_org is null then
    insert into public.research_organizations
      (name, organization_type, registration_number, contact_email,
       status, dpa_accepted_at, dpa_version, approved_at)
    values
      (${sqlStr(ORGANIZATION.name)}, ${sqlStr(ORGANIZATION.organization_type)},
       ${sqlStr(ORGANIZATION.registration_number)}, ${sqlStr(ORGANIZATION.contact_email)},
       'active', now(), '2026-07-04', now())
    returning id into v_org;
  else
    update public.research_organizations set status = 'active' where id = v_org;
  end if;

  select id into v_uid from auth.users where email = ${sqlStr(RESEARCHER.email)};
  if v_uid is null then
    raise exception 'Researcher auth account missing. Run seed_research_account.mjs first.';
  end if;

  update public.profiles
     set role = 'researcher', status = 'active', cnic = ${sqlStr(RESEARCHER.cnic)}
   where id = v_uid;

  -- The account signed up as a patient, so it has a patient_profiles row and
  -- may hold clinical data of its own. Remove it: a researcher must never be a
  -- data subject inside the pool they can query.
  delete from public.patient_profiles where id = v_uid;

  insert into public.researcher_profiles (id, organization_id, job_title, is_org_admin)
  values (v_uid, v_org, 'Principal Investigator', true)
  on conflict (id) do update
    set organization_id = excluded.organization_id,
        is_org_admin = true;

  raise notice 'Researcher ready: % in org %', ${sqlStr(RESEARCHER.email)}, v_org;
end;
$research$;
`;

  const outPath = join(dirname(fileURLToPath(import.meta.url)), 'research_account_promote.generated.sql');
  writeFileSync(outPath, sql, 'utf8');

  console.log(`\nGenerated SQL written to: ${outPath}`);
  console.log('Paste it into the Supabase SQL editor to finish setting up the researcher account.');
  console.log(`\nThen sign in to the research portal (:5175) as:`);
  console.log(`  ${RESEARCHER.email} / ${RESEARCHER.password}`);
}

// Only seed when run directly. Other scripts import RESEARCHER / ORGANIZATION
// from this module, and importing a constant must not trigger a sign-up.
if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((e) => {
    console.error(e);
    process.exitCode = 1;
  });
}
