// Creates a large batch of fake Pakistani test accounts through the ordinary
// public sign-up API (same approach as seed_demo_accounts.mjs), then writes
// fake_pk_data_promote.generated.sql — paste that into the Supabase SQL
// editor afterwards to promote staff roles and create the extra clinics/labs
// (self-service sign-up cannot create lab_worker/receptionist/admin roles or
// clinics; that needs the service-role key, which this script never touches).
//
//   node supabase/tests/seed_fake_pk_data.mjs
//
// Re-running is safe: accounts that already exist are reported and skipped,
// and the generated SQL uses ON CONFLICT / IF NOT EXISTS throughout.

import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  FAKE_PASSWORD, FAKE_PATIENTS, FAKE_DOCTORS, FAKE_LAB_WORKERS,
  FAKE_RECEPTIONISTS, FAKE_EXTRA_ADMIN, FAKE_CLINICS, FAKE_LABS,
  signupMetadata,
} from './fake_pk_data.mjs';

const URL = process.env.SUPABASE_URL || 'https://iikwdtiqvxxatrzahuzo.supabase.co';
const KEY = process.env.SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_4axuKG5-YTuZeHuuzZjuVw_cB5_h-xn';

const client = () => createClient(URL, KEY, { auth: { persistSession: false, autoRefreshToken: false } });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

let created = 0, existing = 0, failed = 0;

// Supabase's sign-up rate limit refills gradually rather than resetting in one
// go, so a single pass through a big batch reliably gets throttled partway.
// Pace every call and, on a rate-limit response, back off and retry the same
// account (up to MAX_RETRIES) instead of giving up.
const PACE_MS = 2000;
const MAX_RETRIES = 8;
const BACKOFF_MS = 65_000; // Supabase's window is ~1 minute-ish; pad it a bit.

async function signUp(email, role, account) {
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    const c = client();
    const { error } = await c.auth.signUp({
      email,
      password: FAKE_PASSWORD,
      options: { data: signupMetadata(role, account) },
    });
    await c.auth.signOut();

    if (!error) {
      created += 1;
      console.log(`created   ${email.padEnd(38)} role ${role.padEnd(10)} cnic ${account.cnic}`);
      return;
    }
    if (/already registered|already been registered/i.test(error.message)) {
      existing += 1;
      console.log(`exists    ${email.padEnd(38)} role ${role}`);
      return;
    }
    if (/rate limit/i.test(error.message) && attempt < MAX_RETRIES) {
      console.log(`throttled ${email.padEnd(38)} retrying in ${Math.round(BACKOFF_MS / 1000)}s (attempt ${attempt + 1}/${MAX_RETRIES})`);
      await sleep(BACKOFF_MS);
      continue;
    }
    failed += 1;
    console.log(`FAILED    ${email.padEnd(38)} ${error.message}`);
    return;
  }
}

const ALL = [
  ...FAKE_PATIENTS.map((a) => [a, 'patient']),
  ...FAKE_DOCTORS.map((a) => [a, 'doctor']),
  ...FAKE_LAB_WORKERS.map((a) => [a, 'patient']),
  ...FAKE_RECEPTIONISTS.map((a) => [a, 'patient']),
  [FAKE_EXTRA_ADMIN, 'patient'],
];

for (const [account, role] of ALL) {
  await signUp(account.email, role, account);
  await sleep(PACE_MS);
}

console.log(`\ncreated ${created}, already existed ${existing}, failed ${failed}`);
console.log(`password for every fake account: ${FAKE_PASSWORD}`);

// ── Generate the promotion SQL ───────────────────────────────────────────────
function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

const lines = [];
lines.push('-- ===========================================================================');
lines.push('-- GENERATED by seed_fake_pk_data.mjs. Do not hand-edit -- rerun the script.');
lines.push('-- Paste this whole file into the Supabase SQL editor and run it once, after');
lines.push('-- seed_fake_pk_data.mjs has created the auth accounts.');
lines.push('-- Safe to re-run.');
lines.push('-- ===========================================================================');
lines.push('');
lines.push('do $fake$');
lines.push('declare');
lines.push('  v_admin uuid;');
for (const c of FAKE_CLINICS) lines.push(`  v_clinic_${FAKE_CLINICS.indexOf(c)} uuid;`);
for (const l of FAKE_LABS) lines.push(`  v_lab_${FAKE_LABS.indexOf(l)} uuid;`);
lines.push('  v_uid uuid;');
lines.push('begin');

// Clinics
lines.push('  -- Clinics ------------------------------------------------------------------');
FAKE_CLINICS.forEach((c, i) => {
  lines.push(`  select id into v_clinic_${i} from public.clinics where name = ${sqlStr(c.name)};`);
  lines.push(`  if v_clinic_${i} is null then`);
  lines.push(`    insert into public.clinics (name, type, phone, address_street, address_city, address_province, status)`);
  lines.push(`    values (${sqlStr(c.name)}, 'clinic', ${sqlStr(c.phone)}, ${sqlStr(c.address)}, ${sqlStr(c.city)}, ${sqlStr(c.province)}, 'active')`);
  lines.push(`    returning id into v_clinic_${i};`);
  lines.push('  end if;');
});

// Labs
lines.push('  -- Diagnostic labs ------------------------------------------------------------');
FAKE_LABS.forEach((l, i) => {
  lines.push(`  select id into v_lab_${i} from public.diagnostic_labs where name = ${sqlStr(l.name)};`);
  lines.push(`  if v_lab_${i} is null then`);
  lines.push(`    insert into public.diagnostic_labs (name, license_number, phone, address_city, address_province, status)`);
  lines.push(`    values (${sqlStr(l.name)}, ${sqlStr(l.license)}, ${sqlStr(l.phone)}, ${sqlStr(l.city)}, ${sqlStr(l.province)}, 'active')`);
  lines.push(`    returning id into v_lab_${i};`);
  lines.push('  end if;');
});

// Extra admin (promoted first so it can approve doctors below)
lines.push('  -- Extra admin ------------------------------------------------------------');
lines.push(`  select id into v_admin from auth.users where email = ${sqlStr(FAKE_EXTRA_ADMIN.email)};`);
lines.push('  if v_admin is not null then');
lines.push(`    update public.profiles set role = 'admin', status = 'active', cnic = ${sqlStr(FAKE_EXTRA_ADMIN.cnic)} where id = v_admin;`);
lines.push('    insert into public.admin_profiles (id, admin_level, can_approve_doctors, can_approve_labs, can_suspend_accounts)');
lines.push("    values (v_admin, 'support_admin', true, true, false)");
lines.push("    on conflict (id) do update set admin_level = 'support_admin';");
lines.push('  end if;');

// Doctors
lines.push('  -- Doctors: approve + assign to a clinic (round-robin) ---------------------');
FAKE_DOCTORS.forEach((d, i) => {
  const clinicVar = `v_clinic_${i % FAKE_CLINICS.length}`;
  lines.push(`  select id into v_uid from auth.users where email = ${sqlStr(d.email)};`);
  lines.push('  if v_uid is not null then');
  lines.push(`    update public.profiles set status = 'active', cnic = ${sqlStr(d.cnic)} where id = v_uid;`);
  lines.push('    insert into public.doctor_profiles');
  lines.push('      (id, pmdc_number, specialization_primary, qualification_mbbs, qualification_fcps,');
  lines.push('       years_of_experience, consultation_fee_pkr, is_available, clinic_id, approved_at, approved_by)');
  lines.push('    values');
  lines.push(`      (v_uid, ${sqlStr(d.pmdc_number)}, ${sqlStr(d.specialization_primary)}, ${d.qualification_mbbs}, ${d.qualification_fcps},`);
  lines.push(`       ${d.years_of_experience}, ${d.consultation_fee_pkr}, true, ${clinicVar}, now(), v_admin)`);
  lines.push('    on conflict (id) do update');
  lines.push('      set clinic_id = excluded.clinic_id, is_available = true,');
  lines.push('          approved_at = coalesce(public.doctor_profiles.approved_at, now()),');
  lines.push('          approved_by = coalesce(public.doctor_profiles.approved_by, v_admin);');
  lines.push('  end if;');
});

// Lab workers
lines.push('  -- Lab workers ---------------------------------------------------------------');
FAKE_LAB_WORKERS.forEach((w, i) => {
  const labVar = `v_lab_${i % FAKE_LABS.length}`;
  lines.push(`  select id into v_uid from auth.users where email = ${sqlStr(w.email)};`);
  lines.push('  if v_uid is not null then');
  lines.push(`    update public.profiles set role = 'lab_worker', status = 'active', cnic = ${sqlStr(w.cnic)} where id = v_uid;`);
  lines.push('    insert into public.lab_worker_profiles (id, lab_id, employee_id, position_title, approved_at)');
  lines.push(`    values (v_uid, ${labVar}, ${sqlStr(w.employee_id)}, ${sqlStr(w.position_title)}, now())`);
  lines.push('    on conflict (id) do update');
  lines.push('      set lab_id = excluded.lab_id, employee_id = excluded.employee_id,');
  lines.push('          approved_at = coalesce(public.lab_worker_profiles.approved_at, now());');
  lines.push('  end if;');
});

// Receptionists
lines.push('  -- Receptionists --------------------------------------------------------------');
FAKE_RECEPTIONISTS.forEach((r, i) => {
  const clinicVar = `v_clinic_${i % FAKE_CLINICS.length}`;
  lines.push(`  select id into v_uid from auth.users where email = ${sqlStr(r.email)};`);
  lines.push('  if v_uid is not null then');
  lines.push(`    update public.profiles set role = 'receptionist', status = 'active', cnic = ${sqlStr(r.cnic)} where id = v_uid;`);
  lines.push('    insert into public.receptionist_profiles (id, clinic_id, employee_id, approved_at)');
  lines.push(`    values (v_uid, ${clinicVar}, ${sqlStr(r.employee_id)}, now())`);
  lines.push('    on conflict (id) do update');
  lines.push('      set clinic_id = excluded.clinic_id, employee_id = excluded.employee_id,');
  lines.push('          approved_at = coalesce(public.receptionist_profiles.approved_at, now());');
  lines.push('  end if;');
});

// Patients: CNIC backfill + address/emergency contact (trigger already set blood_group + health_card_number)
lines.push('  -- Patients: CNIC backfill + address/emergency contact ------------------------');
FAKE_PATIENTS.forEach((p) => {
  lines.push(`  select id into v_uid from auth.users where email = ${sqlStr(p.email)};`);
  lines.push('  if v_uid is not null then');
  lines.push(`    update public.profiles set cnic = ${sqlStr(p.cnic)} where id = v_uid and cnic is distinct from ${sqlStr(p.cnic)};`);
  lines.push('    update public.patient_profiles set');
  lines.push(`      address_city = ${sqlStr(p.city)}, address_province = ${sqlStr(p.province)},`);
  lines.push(`      emergency_contact_name = ${sqlStr(p.emergency_contact_name)}, emergency_contact_phone = ${sqlStr(p.emergency_contact_phone)}`);
  lines.push('    where id = v_uid;');
  lines.push('  end if;');
});

lines.push('');
lines.push("  raise notice 'Fake Pakistani test data promotion complete.';");
lines.push('end;');
lines.push('$fake$;');

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, 'fake_pk_data_promote.generated.sql');
writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
console.log(`\nGenerated SQL written to: ${outPath}`);
console.log('Paste its contents into the Supabase SQL editor and run it to finish the promotion.');
